export const CREATE_ACHIEVMENT = 'CREATE_ACHIEVMENT';
export const GET_ACHIEVMENTS = 'GET_ACHIEVMENTS';
export const UPDATE_ACHIEVMENT = 'UPDATE_ACHIEVMENT';
export const DELETE_ACHIEVMENT = 'DELETE_ACHIEVMENT';
export const OPEN_ACHIEVMENT_DIALOG = 'OPEN_ACHIEVMENT_DIALOG';
export const CLOSE_ACHIEVMENT_DIALOG = 'CLOSE_ACHIEVMENT_DIALOG';
export const ON_CHANGE_ACHIEVMENT_FIELD = 'ON_CHANGE_ACHIEVMENT_FIELD';
