import { makeStyles } from '@material-ui/core/styles';
export const useComponentStyles = makeStyles((theme) => ({
  wrapper: {
    display: 'flex',
    borderRadius: 500,
    minHeight: 150,
    width: '100%',
    border: '2px solid black',
  },
  title: {
    textAlign: 'center',
    fontSize: 24,
    fontWeight: 'bold',
    color: theme.palette.primary.main,
  },
  imageWrapper: {
    // height: '100%',
    position: 'relative',
    minWidth: 150,
    width: 150,
    maxWidth: 150,
    overflow: 'hidden',
    borderRadius: 500,
  },
  image: { width: 150, height: 150, overflow: 'hidden', objectFit: 'cover' },
  points: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    textAlign: 'center',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    color: 'white',
    zIndex: 10,
    background: 'rgba(0,0,0,0.4)',
    fontSize: 36,
  },
  description: {
    paddingLeft: theme.spacing(3),
    paddingRight: theme.spacing(3),
  },
  titleWrapper: {},
  topPart: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    paddingLeft: theme.spacing(3),
    paddingRight: theme.spacing(5),
    paddingTop: theme.spacing(1),
  },
  bottomPart: {},
  actionsWrapper: {},
  content: {
    width: '100%',
  },
  '@media (max-width: 1260px)': {},
  '@media (max-width: 960px)': {},
  '@media (max-width: 640px)': {},
}));
